### ISSUE TITLE
FEL analysis giving Bad Request

### ISSUE THREAD

**Issue by nprovart** [veg/datamonkey-js#100]
I was trying to do a FEL analysis with Datamonkey and even if I try with the example data set (the flu.fasta one), use defaults then select all or leaf nodes I get a "400 bad request" error (this is the link that appears http://datamonkey.org/fel/<%=%20fel._id%20%>/select-foreground, something doesn't seem kosher with that, it looks like the job ID is not getting properly interpolated?

**Comment by stevenweaver** [comment]
Dear @nprovart, 

Code from our development branch somehow made its way into production. We've resolved the issue. The fix should be reflected on the main site after a schedule restart of 17:00 ET. 

Thank you for using Datamonkey, 
Steven
