### ISSUE TITLE
[HIV-TRACE] runtime errors

### ISSUE THREAD

**Issue by spond** [veg/datamonkey-js#104]
Dear @stevenweaver,

There seem to be issues with HIV-TRACE when edge filtering or contaminant removal is turned (exceptions returned). Could you please run a few tests to confirm? If you can't, I'll show you the problematic dataset tomorrow.

We want HIV-TRACE to be running smoothly because the paper is about to come out. 

Best,
Sergei

**Comment by stevenweaver** [comment]
Dear @spond, 

I already have a log of the job and its parameters that caused an exception at 15:41 on Jan 30th. I will take a look. 

Best,
Steven
