### ISSUE TITLE
Issue with branch display with fitted tree

### ISSUE THREAD

**Issue by razorhog** [veg/datamonkey-js#118]
hello,
I have run an analysis using aBSREL that creates the desired output data, but when I hover over the branches of the fitted tree with the mouse cursor, the branch information does not appear. I have run it on different browsers but encountered the same problem. thank you for your help.

**Comment by rdvelazquez** [comment]
Thanks for bringing this to our attention @razorhog! 
The issue will be addressed by the bootstrap 4 upgrade and [#158](https://github.com/veg/hyphy-vision/pull/158). I'll close this issue once the bootstrap 4 upgrade is merged.
