### ISSUE TITLE
Cosmetic issues with error reporting

### ISSUE THREAD

**Issue by spond** [veg/datamonkey-js#163]
When the file uploaded is too large, the error message that is displayed has HTML tags in it:

<img width="905" alt="screen shot 2018-12-14 at 3 59 38 pm" src="https://user-images.githubusercontent.com/1018513/50027219-6c8cce80-ffb9-11e8-806f-73e0776e18e5.png">

**Comment by rdvelazquez** [comment]
Addressed by https://github.com/veg/datamonkey-js/commit/9602e880e17aef22ae0d3a47a2deaaa9c9bbf2bb
