### ISSUE TITLE
FEL and SLAC not running?

### ISSUE THREAD

**Issue by nprovart** [veg/datamonkey-js#164]
I am attempting to run SLAC and FEL analyses but the DataMonkey server won't even give me a ticket number :(  Can you please investigate...SLAC worked for me yesterday but now it's not working today (FEL was not working yesterday, and continues to hang today). Thanks!!

**Comment by rdvelazquez** [comment]
Dear @nprovart,

Thanks for letting us know about this issue. We are experiencing higher than normal usage on datamonkey which is making parts of the site unresponsive. We are currently working to address the issue and will let you know when we've addressed the issue and things are back to normal. 

Best,
Ryan

**Comment by rdvelazquez** [comment]
Dear @nprovart,

FEL and SLAC are now both working again. Thanks again for letting us know about the issue, very helpful!

Best,
Ryan

**Comment by nprovart** [comment]
Thanks, @rdvelazquez and @spond! I've just added another ticket about the sorting by dN-dS scores in the output table. It is wonky... Nick
