### ISSUE TITLE
sorting by dN-dS values in output tables

### ISSUE THREAD

**Issue by nprovart** [veg/datamonkey-js#167]
When I try to sort the output table (any type of analysis) by dN-dS, the sorting isn't as I would expect it to be, that is from largest to smallest or smallest to largest. It is kind of random (sometimes the largest absolute value does appear at the top of the table but other times not)...or I am not understanding the behaviour of the sort function. Thanks!

**Comment by rdvelazquez** [comment]
Hi @nprovart Thanks for letting us know about the issue. I've noticed something similar in the SLAC site table: zero values for dN-dS are always at the top (above negative and positive values). I believe these values for dN-dS that are shown as zero are actually 0/0 (i.e. no synonymous or non-synonymous mutations) and are therefore handled differently than the other values.

Does this sound like the behavior you were seeing?
