### ISSUE TITLE
[Costmetic] Overlapping axis ticks labels

### ISSUE THREAD

**Issue by spond** [veg/datamonkey-js#169]
On less than large widescreen viewports (e.g. MacBook Pro), axis tick labels run into one another. This example is from BUSTED, but I would imagine other charts are similarly affected.

<img width="995" alt="screen shot 2019-01-10 at 3 24 11 pm" src="https://user-images.githubusercontent.com/1018513/50995033-e0a09080-14eb-11e9-95dd-4619ee6bb0a1.png">

**Comment by rdvelazquez** [comment]
Addressed by https://github.com/veg/hyphy-vision/commit/ed93db1b47340f79addfe0409c4dab3edf082d09

Before:
<img width="941" alt="flu before" src="https://user-images.githubusercontent.com/25244432/51182009-c8899200-189a-11e9-8f32-9b72724267e6.png">

After:
<img width="946" alt="flu after" src="https://user-images.githubusercontent.com/25244432/51182016-cf180980-189a-11e9-90b0-fdd17813bbd3.png">
