### ISSUE TITLE
BGM Export Options

### ISSUE THREAD

**Issue by rdvelazquez** [veg/datamonkey-js#179]
BGM only has `save json` and `view json`  
<img width="956" alt="screen shot 2019-02-22 at 10 43 14 am" src="https://user-images.githubusercontent.com/25244432/53253224-bf0bfa80-368e-11e9-864c-96b19d65d9ca.png">

It should have additional export options like the other methods:  
<img width="979" alt="screen shot 2019-02-22 at 10 43 37 am" src="https://user-images.githubusercontent.com/25244432/53253223-bf0bfa80-368e-11e9-9ea8-9e550671a513.png">

**Comment by ArtPoon** [comment]
It should also be possible to export the edge list as a CSV or a DOT file.

**Comment by rdvelazquez** [comment]
Closed by #185
