### ISSUE TITLE
Feature Request: TN93 Distance Download Option

### ISSUE THREAD

**Issue by jwertheim** [veg/datamonkey-js#187]
I have received several requests for an option to download the TN93 csv (and aligned fasta file) on the public HIV-TRACE website, hosted on Datamonkey.

**Comment by kjlevitz** [comment]
Hello @jwertheim, 

I wanted to reach out to let you know that we are currently working on implementing a download button. I should have it finished this week.

Thank you,

Kevin Levitz

**Comment by kjlevitz** [comment]
@jwertheim,

The download button has been added to the HIV-Trace results page. You will find it on the last tab under TN93 results.

Thank you,

Kevin Levitz

**Comment by rdvelazquez** [comment]
@kjlevitz The download that I'm seeing looks to only be the fasta file and not the actual tn-93 distances. Sorry I missed that in my original pull request. Can you confirm that that is the case and see if you can get both the fasta and the tn-93 distances to download?

**Comment by rdvelazquez** [comment]
As of https://github.com/veg/datamonkey-js/commit/c0c2dac65408b9ad2779dc7810374a239e592009, the tn93 distance file is being correctly downloaded. Thanks @kjlevitz!
