### ISSUE TITLE
BUSTED ignoring No SRV option

### ISSUE THREAD

**Issue by srwis** [veg/datamonkey-js#196]
Hi yall,

It seems like BUSTED is ignoring the No SRV option when it's chosen. I checked this twice with the same file: 
[allOis1_D_300_replicate.13.txt](https://github.com/veg/datamonkey-js/files/3291909/allOis1_D_300_replicate.13.txt)

Here's one of the tests:
http://staging.datamonkey.org/busted/5d03ef041e9b8e1cd9a29e01
[log (1).txt](https://github.com/veg/datamonkey-js/files/3291906/log.1.txt)

Thanks,
Sadie

**Comment by rdvelazquez** [comment]
You're correct. We hadn't pulled in @stephenshank 's busted SRV PR (https://github.com/veg/datamonkey-js-server/pull/77) into datamonkey-js-server yet. I just pulled that in and updated the staging instance. Sorry about that. 

https://github.com/veg/datamonkey-js-server/pull/77
