### ISSUE TITLE
aBSREL on Datamonkey server stopped

### ISSUE THREAD

**Issue by KaptainRose** [veg/datamonkey-js#199]
I'm running analyses on a 126 taxa/96 bp alignment on the Datamonkey server. FEL and BUSTED run beautifully but my aBSREL analyses keep stopping and the abort message directs me to opening up an issue here.
For context, I chose all branches on my user-defined tree except for the branches leading to the two out groups.
Link to the job: https://datamonkey.org/absrel/5d9f2367a4e2ac3ef454fda3
Thanks!

**Comment by stevenweaver** [comment]
Datamonkey has been updated to use HyPhy 2.5.1
