### ISSUE TITLE
Testing DM pages

### ISSUE THREAD

**Issue by srwis** [veg/datamonkey-js#291]
List of datamonkey methods to test with @aglucaci and @jzehr  

- [x] aBSREL
Assigned to: @aglucaci 
Tested:

- [x] Spidermonkey/BGM
Assigned to: @jzehr 
Tested:

- [x] BUSTED {GIT HUB ISSUE: UNABLE TO RECREATE #390 [x]}
Assigned to: @srwis 
Tested:

- [x] CONTRAST-FEL
Assigned to: @srwis 
Tested:

- [x] FADE
Assigned to: @jzehr 
Tested:

- [x] FEL
Assigned to: @srwis 
Tested:

- [x] FUBAR
Assigned to: @aglucaci 
Tested:

- [x] GARD {GITHUB ISSUE RESOLVED #345 - [x] }
Assigned to: @jzehr 
Tested:

- [ ] HIV-TRACE
Assigned to: @jzehr 
Tested:

- [x] MultiHit {Reported as resolved my S. Weaver}
Assigned to: @aglucaci 
Tested:

- [x] MEME
Assigned to: @aglucaci 
Tested:

- [x] RELAX
Assigned to: @jzehr 
Tested:

- [x] SLAC
Assigned to: @srwis 
Tested:

**Comment by srwis** [comment]
# BUSTED 
- tested with SARS-COV-2 S with SRV and without 
- everything was fine job showed up in the queue and all the files that you can download did.
- the only issue is that the font for the labels on the tree are incredibly tiny and it makes it so the png tree files are unreadable ![tree](https://user-images.githubusercontent.com/20407008/82588228-74ff1680-9b68-11ea-9e2d-b6ebe8d9b0e7.png)

- I did manage to break it at one point but have yet to be able to recreate the issue.
[log (2).txt](https://github.com/veg/datamonkey-js/files/4663803/log.2.txt)

**Comment by srwis** [comment]
# Contrast-FEL
## HIV-RT test:
- http://www.datamonkey.org/contrast_fel/5ecd78db81949e0be7d93a9e
- failed at first with an error about branch labels but was okay upon resubmission.
- interestingly the resubmitted job has the same URL as the one that originally errored, so there's no record of it on the user side. I linked it before I restarted it in the DM slack channel. 
- if you click the top node the option box floats out of bounds like so:
![Screen Shot 2020-05-26 at 4 17 01 PM](https://user-images.githubusercontent.com/20407008/83040060-dada1b00-a00c-11ea-906b-74068468d75b.png)


## HIV-ENV test:
- http://www.datamonkey.org/contrast_fel/5ecd7e6481949e0be7d94162

## Cytb test:
- http://www.datamonkey.org/contrast_fel/5ecd807181949e0be7d941f5

## general comments:
- when you pick total branch length for the site plot values above ~10 are cutoff. 
![datamonkey-chart (5)](https://user-images.githubusercontent.com/20407008/83040290-18d73f00-a00d-11ea-8785-289697938b6a.png)
- no easy way that I was able to see to select branches based on label like HSX vs MSM for HIV env gene
- links for click here for more info could maybe be this instead of just FEL: http://hyphy.org/methods/other/contrast-fel/ or http://hyphy.org/methods/other/evo/ (I'm assuming the citation will update once the paper is published.)

**Comment by jzehr** [comment]
# BGM 

### Rubisco (C3 vs C4) test:
- job: http://www.datamonkey.org/bgm/5ecea7fbd49cd511eec745c4
- ran no problem

### HIV_RT.nex 
- job: http://datamonkey.org/bgm/5ecea74ed49cd511eec743b3
- ran no problem

### CYTB
- job: http://www.datamonkey.org/bgm/5ecea7fdd49cd511eec746fa
- ran no problem

### BCTFull 
- job http://www.datamonkey.org/bgm/5eceb4bbd49cd511eec750ee
- ran no problem 

## General Comments:
- I think an alignment component (feature) would be great here, to highlight the co-evolving sites that were found by the tool

**Comment by jzehr** [comment]
# GARD

### HIV_RT Site-to-site rate variation: `none`
- job: http://datamonkey.org/gard/5ecea9c6d49cd511eec74a19
- ran no problem but no Vision page appeared when I clicked on the link

### HIV_RT Site-to-site rate variation: `General Discrete`
- job: http://datamonkey.org/gard/5ecea9ced49cd511eec74bf7
- ran no problem but no Vision page appeared when I clicked on the link

### HIV_RT Site-to-site rate variation: `Beta-Gamma`
- job: http://datamonkey.org/gard/5ecea9d5d49cd511eec74dd6
- ran no problem but no Vision page appeared when I clicked on the link

**Comment by jzehr** [comment]
# RELAX

## HIV_RT: 
- when prompted to select `Test Branches` and `Reference Branches`, if you select a node too close to the top of the screen, the box will get cut off, rendering it such that you cannot see all the options:
![Screen Shot 2020-05-27 at 3 07 38 PM](https://user-images.githubusercontent.com/38324371/83062121-23ed9780-a02c-11ea-8615-0c5fa3ae81c1.png)

**Comment by srwis** [comment]
# FEL
## HIV-RT run:
- http://www.datamonkey.org/fel/5ecebb97d49cd511eec75590
- w/ SRV selected leafs only
- ran fine

## HIV env
- http://www.datamonkey.org/fel/5ecebbead49cd511eec75771
- w/ SRV all branches
- ran fine

## Cytb
- http://www.datamonkey.org/fel/5ecebc2dd49cd511eec757fa
-  w/ SRV and internal only
- ran fine 

## General comments:
- same issue where the site graph is cutting things off. Is this to control outliers making it unreadable?: 
![datamonkey-chart (6)](https://user-images.githubusercontent.com/20407008/83064043-243b6200-a02f-11ea-94ea-7770805e9ea8.png)
- minor typo here where the symbol isn't showing:
![Screen Shot 2020-05-27 at 3 30 05 PM](https://user-images.githubusercontent.com/20407008/83064400-b6dc0100-a02f-11ea-9b5d-e1b43e082d26.png)
- also some weird behavior between the site table and chart. When you sort a column in the table, then pick a dif parameter in the chart the table unsorts itself. can post video in slack if needed.

**Comment by stellaparadis** [comment]
# Contrast-FEL

**Data: HIV-1 reverse transcriptase**
**Genetic Code: Universal code**
**Select Branch Page:**
[http://www.datamonkey.org/contrast_fel/5ed66bded49cd511eec8f32d/select-foreground](http://www.datamonkey.org/contrast_fel/5ed66bded49cd511eec8f32d/select-foreground)

**Comment based on user perspective:** 
* It would be nice to select multiple branches based on the name of the sample.
Ex: If it has 'T' in front of the name, then bin them in one group vs 'N' group, etc... 

* It would be nice to tag in a more obvious way.
Ex: Make a column 'T' and select multiple branches and drag them to that column etc...

*  There are typos to "Select Test Branches" icons.
"Sort deepest clades to the (bototm)"
"Sort (deepsest) clades to the top"

* Some of the branch names at the far right gets slightly cut off. 

![branch_names](https://user-images.githubusercontent.com/14365247/83977278-5a999c80-a8cd-11ea-98a5-151807f048e1.PNG)

**Result Page:**
[http://www.datamonkey.org/contrast_fel/5ed66bded49cd511eec8f32d](http://www.datamonkey.org/contrast_fel/5ed66bded49cd511eec8f32d)

**Comment based on user perspective:** 

* Info copying icon does not have a "hovering description" of what the icon is about until I click it and see "Copied!" 

* On the website, the description ends in "ContrastFEL found evidence of" and then the next line is "Found 0 sites with different Overall dN/dS." It would be perhaps more helpful to spell out the below message on the website?
"Contrast-FEL found evidence of pervasive positive/diversifying selection at 0 sites in your alignment. In addition, Contrast-FEL found evidence with p-value 0.5 of pervasive negative/purifying selection at 0 sites in your alignment. Contrast-FEL did not find evidence for either positive or negative selection in the remaining 335 sites in your alignment."
* The explanation of foreground branches could be helpful maybe? 

* For the ContrastFEL Table, the current subs column description is "Substitutions mapped to Foreground branches." Is it the number of substitutions? 

* Maybe adding the significance of each column title would be helpful. Ex: What is the significance of the total branch length?" 

* For the Contrast-FEL Site Plot, what are betas, is_positive, and is_negative? What is the difference between beta(Foreground) vs betas?

* For the Fitted tree, some of the branch names at the far right gets slightly cut off when using the right side alignment option. 

* Also, Hide Legend and GrayScale checkbox responses seem to be a little slow. Or maybe it's just my computer. 

* What does GrayScale do? Nothing seemed to change. 

* For the Model fits, is there a reason why result rows flicker or change to the lighter color background when I hover over them?

**Comment by srwis** [comment]
Quick MultiHit comment from doing the video:

I like the picture keys (dice/compass) here but think they need to be consistent: 
![image](https://user-images.githubusercontent.com/20407008/84047427-401cfd00-a979-11ea-823b-10e1045f914b.png)

**Comment by stellaparadis** [comment]
# Multi-HIT

**HyPhy FitMultiModel Page:** 
[http://hyphy.org/methods/other/FitMultiModel/](http://hyphy.org/methods/other/FitMultiModel/)

* The first question may be phrased a little weird? 
	* It says “What biological question is the method designed to answer?” 
	* Should it say instead, “What is the biological question that the method was designed to answer?”
	* Then the answer is “Does a data set have evidence of multiple simultaneous hits (MH) and to what (exitent: there is a typo)?”
	* In the answer, maybe it is a good idea to include a short description of what multiple simultaneous hits are.

* Another question says, “What is the statistical procedure and statistical test is used to establish significance for this method?”
	* Should it say instead, “What are the statistical procedure and (the) statistical test (that) is used to establish significance for this method?”

* For the parameter table: the omega row mentions GDD distribution. Brief description or simply stating what it stands for could be helpful.

**Datamonkey Multi-HIT Page:**
[http://datamonkey.org/multihit](http://datamonkey.org/multihit)

* It would be nice to include descriptions of Triple Islands and Rate Classes on the page itself instead of hovering description or indicate somewhere that if we hover over the words, the description shows.
	* I know that it has cleaner look without the description, but as a user, maybe it is more helpful to see the info.

* Since multi-hit is a complex program, it would be nice to link above HyPhy FitMultiModel Page on this page so that people don’t need to look for the information.

**Datamonkey Multi-HIT Results Summary Page:**

Data: HIV RT
Default parameters, rate classes, no triple islands
[http://datamonkey.org/multihit/5ecf01d4d49cd511eec76b1b](http://datamonkey.org/multihit/5ecf01d4d49cd511eec76b1b)

* When I click “Export” and hover over different options, the green color block is not fully coloring the row. It is not important but just thought that it would be nicer to have full row colored.

* The left-hand side tab (that has options for summary, site plot, table, and substitution plot) is too close together with the bar that divides the actual results page.

![letter_close_to_bar](https://user-images.githubusercontent.com/14365247/84619227-7fc87500-aea2-11ea-9b35-48b8923ad781.PNG)

* Similar to  Contrast-FEL, the “Copied!” icon does not have the hovering description. It shows “Copied!” after it is clicked.

* Also, the copied message does not have the actual content. It has “[object Object]”.

* When I hover over the Likelihood Test Results boxes, I get a line in the middle of the boxes. Just FYI.

* For the Model Test Statistics Per Site Plot, maybe it would be nice to have some info on the Evidence Ratios vs Site Log Likelihood selections.

* When I export Model Test Statistics Per Site Table, in the exported CSV file, the table's title row is a bit weird.
	* Example: \<i class="fas fa-dice-three fa-2x">\</i> vs. \<i class="fas fa-dice-two fa-2x">\</i>" shows up. 
	* It is supposed to be 3H vs 2H

* When I hover over the dice icons in the table, I get 2 hovering description boxes, one in black and the other one in white.

* When I export the circle graph, the exported image does not include the legend information even after I check for the legend.

**Comment by aglucaci** [comment]
For Contrast-FEL wanted to add a short additional note on @stellaparadis analysis. The HyPhy vision page does not seem to be highlighting sites that were found in the data results table.

**Comment by srwis** [comment]
# SLAC
## HIV-ENV Run:
 - http://www.datamonkey.org/slac/5ec8013b6fa3ed0c9e043686
 - sometimes when you sort by dn-ds in the site table site 1 stays on top

## HIV-RT Run
- http://www.datamonkey.org/slac/5ee7d3c230dd9a22dc33a3aa
- looks like every ran fine

## CytB
 - http://www.datamonkey.org/slac/5ee7d48530dd9a22dc33a58d
- looks like every ran fine

## General notes:
 - maybe rearrange the fitted tree and the phylo alignment viewer so the fitted tree comes last since the phylo alignment viewer is more interesting
- may also want an svg export option for phylo alignment viewer as with larger trees png gets blurry when you zoom.

**Comment by aglucaci** [comment]
**## aBSREL**

Export > Save JSON, should have a useful filename, perhaps derived from the input filename rather than the generic "results.json"

Tested with the Rubisco dataset here (All branches):
http://datamonkey.org/absrel/5ecf0019d49cd511eec76475

Missing branches on tree

![Screen Shot 2020-06-15 at 6 41 31 PM](https://user-images.githubusercontent.com/43097993/84712947-e055c180-af37-11ea-96db-fd41123cddc9.png)

Tested with the Rubisco dataset here (Only internal branches) and looks fine.

Tested with the Rubisco dataset here (leaf nodes) and looks fine. And we are missing branches again.
![Screen Shot 2020-06-15 at 6 43 25 PM](https://user-images.githubusercontent.com/43097993/84713097-43475880-af38-11ea-830b-ed3d379bc28d.png)

Tested on HIV-RT dataset and got error "-bash: warning: setlocale: LC_ALL: cannot change locale ("en_US.UTF-8")
manpath: can't set the locale; make sure $LC_* and $LANG are correct
bash: warning: setlocale: LC_ALL: cannot change locale ("en_US.UTF-8")
=>> PBS: job killed: walltime 259208 exceeded limit 259200
HYPHYMPI terminated.
Error:
HyPhy killed by signal 15"

Will need to rerun.

**Comment by aglucaci** [comment]
Short note, Contrast-FEL and FEL both output a *FEL.json, propose an alternative where Contrast-FEL outputs to *CFEL.json

**Comment by aglucaci** [comment]
Also for BUSTED "BUSTED without synyonymous rate variation found evidence (LRT, p-value = 0.001 ≤ .05) of gene-wide" Misspelled word "synyonymous"

**Comment by aglucaci** [comment]
aBSREL on Hyphy Vision, the datatable stretches beyond the limit of the frame. 
![Screen Shot 2020-06-17 at 5 29 32 PM](https://user-images.githubusercontent.com/43097993/84952626-41100600-b0c0-11ea-9663-80cf3aab2b72.png)

**Comment by jzehr** [comment]
I noticed that when  you render a window to a smaller size, the options to ```Load``` a file or select another tool from the ```Tools``` button is no longer available.

<img width="838" alt="rendering" src="https://user-images.githubusercontent.com/38324371/85283076-c4cc4880-b45a-11ea-9727-62c16bb9cb36.png">

**Comment by srwis** [comment]
As an add-on, can yall (@aglucaci @jzehr @stellaparadis) take a look at http://www.datamonkey.org/help

and see with there's anything you'd add or take out.

**Comment by stellaparadis** [comment]
# FUBAR
**HyPhy FUBAR Page:** 
[http://datamonkey.org/fubar](http://datamonkey.org/fubar)

* Link to detailed FUBAR description page would be nice.

* Implications of “Number of grid points” and “Concentration parameter of the Dirichlet prior” would be helpful.

**Fast Unconstrained Bayesian AppRoximation results summary Page:** 
Data: HIV RT
Default parameters (# grid points, Concentration parameter of the Dirichlet prior)
[http://datamonkey.org/fubar/5eda4bb9d49cd511eec9fa5c](http://datamonkey.org/fubar/5eda4bb9d49cd511eec9fa5c)

* For the title of the page, maybe it is helpful to also write out FUBAR before the long name.

* For the part where it talks about the general result, it would be nice to include “Copy Result” icon. This will not only help users to copy the general result easily but also allow us to match the website format with other newer methods.

* Maybe it would be helpful to explain what episodic vs pervasive selection are in the result.

* For the Posterior rate distribution graph, when I export the image, the graph does not have a title. Maybe it could be useful to have some sort of title.

* For the FUBAR Site Table, the exported table has column headers that are slightly off. For instance, &alpha; is written as \&alpha;

* For the Fitted tree, depending on the shape of the tree, the last letter or digit of the name gets cut off slightly.
![fitted_tree](https://user-images.githubusercontent.com/14365247/85981560-63ecc500-b9b2-11ea-8adf-0a86c528066c.PNG)

* For Model fits table, Rate distributions column is missing, and I am not sure if it is normal that way. Also, on the bottom of the table, it mentions MG94, but for this particular analysis, I do not see MG94. I see Nucleotide GTR model instead. Just FYI.

**Comment by stellaparadis** [comment]
# Help Page
http://www.datamonkey.org/help

@srwis There are some very minor things.

* “our” and “Github” link needs a space.
* “when,” and “Suzuki and Nei” link needs a space.
* Link for “Yang” does not work. It stays in the help page.
* “Selection using HyPhy” link and “ )” does not need a space.
* “Codon-MSA” link and “or” needs a space.
* “accept” and “IUPAC nucleotide characters” link needs a space.
* There are mixed formats throughout the document: DataMonkey vs Datamonkey.
* For Handling Ambiguities, there are no explanations for Skip and GapMM. 
* “Choosing significance levels” needs to be “Choosing Significance Levels” insead.

**Comment by stellaparadis** [comment]
# MEME
**MEME Detect Individual Sites Subject to Episodic Diversifying Selection Page:** 
http://datamonkey.org/meme

* Maybe it would be cool to put what MEME stands for on the page. 

* Link to MEME description page could be helpful.

**Mixed Effects Model of Evolution results summary Page:** 
http://datamonkey.org/meme/5ecf0147d49cd511eec76895
Data: HIV RT
Default parameters 

* For the title of the page, maybe it is helpful to also write out MEME before the long name.
* For the part where it talks about the general result, it would be nice to include “Copy Result” icon. This will not only help users to copy the general result easily but also allow us to match the website format with other newer methods.
* For the MEME Table, the exported table has column headers that are slightly off. For instance, &alpha; is written as \&alpha;
* For the MEME Site Plot, when I export the image, the graph does not have a title. Maybe it could be useful to have some sort of title.
* For MEME Branch EBF Table, it could be helpful to include a brief purpose description of the EBF Table.

**Comment by srwis** [comment]
I noticed the for BUSTED, there's the phylo alignment tab on the left navigation but that visualization component is not actually on the page.
