### ISSUE TITLE
[SLAC] Partitioned analyses and annotated tree widget

### ISSUE THREAD

**Issue by spond** [veg/datamonkey-js#292]
If an analysis includes multiple partitions, several issues occur with the tree widget that maps substitutions onto branches.

1. You cannot ask to visualize a site by its alignment coordinate (only partition coordinate); this makes the process of finding the right site to display arduous (you have to "map" to partition coordinates manually), e.g. try to view site 

2. If partition 1 has X sites, you cannot request to view site X+k (k>0) even if other partitions have it.

**Comment by stephenshank** [comment]
Dear @spond,

Thanks for reporting! Agreed that there should be better support for multiple partitions.

Re: 2, would you like the ability to view multiple sites belonging to the same partition, as was done for the related BUSTED widget? If so, I think the amino acid/codon feature will have to be disabled when viewing multiple sites, unless there is a better solution.

**Comment by spond** [comment]
Dear @stephenshank,

For **2** I just meant that it is currently impossible to view, say, site 350 in partition 2 if there are only 300 sites in partition 1. Seems like the input element accepting site indices is bound by the # of sites in the first partition.

Best,
Sergei

**Comment by stephenshank** [comment]
Now live on Datamonkey: http://datamonkey.org/slac/5eeb7d6964d1164953f0898a
