### ISSUE TITLE
502 error on aBSREL completed job

### ISSUE THREAD

**Issue by shablak** [veg/datamonkey-js#451]
I received an email stating that my aBSREL job was complete, but when I click the link in the email, instead of getting the nice markdown file, I get a 502 - Bad Gateway. I checked on multiple browsers and devices. Is there a server problem or another issue? I have used aBSREL on datamonkey in the past without issue.

**Comment by stevenweaver** [comment]
Dear @shablak, 

Thank you for reporting this issue. It was a problem with our web server process and should now be working as expected after restarting. 

Best,
Steven
