### ISSUE TITLE
GARD: Extended Run Times

### ISSUE THREAD

**Issue by venuraherath** [veg/datamonkey-js#474]
Hi Dr. Pond,

I have a question regarding the following job currently running  
Ticket #: 1526564.new-silverback

They are running for an extended time and wondering if you can suggest any way to optimize the run to minimize time while not burdening your server too much. I don't have an access to HPC so I can't go forward with HYPHY installation.
This run includes ~140 viral sequences and size ~10kb/per seq. 

I really appreciate your input in this regard.
Have a nice day,

Venura

**Comment by stephenshank** [comment]
Dear @venuraherath,

It appears as though you are trying to run a GARD job. Our [usage statistics](http://datamonkey.org/stats#) indicate that while some jobs that are of comparable size to what you've submitted have completed with the resources we provide (24 processors for 3 days), it is definitely at the upper end of what Datamonkey can handle. Unfortunately not all jobs of this size are guaranteed to run to completion.

Nevertheless, I did notice that you appear to be running GARD in `Normal` mode. There is a `Faster` option, enabled by default, that might help. Outside of that you may want to downsample sequences... a very simple approach would be to remove enough that are closely related to enable computational feasibility.

<img src=https://user-images.githubusercontent.com/8673708/118496899-900c5400-b6f2-11eb-8d4c-f1fe8d691477.png  width="400">


Best,
Stephen
