### ISSUE TITLE
Relax tree topology

### ISSUE THREAD

**Issue by NickSeg** [veg/datamonkey-js#593]
Greetings,

I am a new user of RELAX. 

I am using as the input the attached file named "Alignment plus tree in fasta.txt" as the input (except that the ".fasta" extension had to be changed to ".txt" here so that the webpage would let me upload the file).

Datamonkey shows me a tree that is presented as a screen shot in the file "Tree as seen in datamonkey". The tree looks different from the tree I expect from the tree file ("tree in newick format.txt"). The tree I expect to see is attached as a PDF file derived from the software FIgTree ("tree in pdf as seen in figtree"). 

Some of the differences between the trees is very stark. For example, "Ectocarpus_siliculosus_MYBgene1" is supposed to be closer to "Cyanophora_paradoxa_DIVlike1" than "Bremia_lactucae_MYBgene1", but that is not at all the case in the tree displayed by datamonkey. Does this discrepancy between the two trees affect the analysis?

Thank you,
Aniket

[Alignment plus tree in fasta.txt](https://github.com/veg/datamonkey-js/files/9030525/Alignment.plus.tree.in.fasta.txt)
[tree in newick format.txt](https://github.com/veg/datamonkey-js/files/9030526/tree.in.newick.format.txt)
![Tree as seen in datamonkey](https://user-images.githubusercontent.com/108542326/176938574-7a75cdfa-3600-48b3-8860-b35d1ffaa874.png)
[tree in pdf as seen in figtree.pdf](https://github.com/veg/datamonkey-js/files/9030527/tree.in.pdf.as.seen.in.figtree.pdf)

**Comment by stevenweaver** [comment]
Dear @NickSeg, 

Thank you for reporting this issue. It has been reproduced. Looking into what the problem is now. 

Best,
Steven

**Comment by stevenweaver** [comment]
Dear @NickSeg, 

Can you please ensure that the tree labels match the headers in the FASTA file and try again?

Best,
Steven
<img width="1728" alt="Screen Shot 2022-07-01 at 12 33 23 PM" src="https://user-images.githubusercontent.com/535261/176944924-55150f8f-a2af-46cc-b78b-2475e2c936ff.png">

**Comment by NickSeg** [comment]
Hi,

Making the names match didn't help. But when I trimmed the names down to a
very short identifiers did help. Is there a size limit to taxon names?
If it is okay, I had a more sciencey question about RELAX. I was wondering
whether you could kindly help.

I am working on a group of MYB genes, which are protein coding genes with a
conserved region coding for MYB domains.



In my clade of MYB genes, the first-diverging group has a certain MYB
domain (let's call it domain-1), the second-diverging group also has this
MYB domain-1 (and has additionally acquired another MYB domain), and the
third-diverging group has lost this MYB domain-1 (and kept the new MYB
domain).



I want to test whether the MYB domain-1 in the second-diverging group is
under relaxed selection and is on its path to being lost. (I think the loss
is happening because starting this group, a new MYB domain has appeared and
has likely taken over the function.). I will infer the phylogenetic
relationships using the entire coding region of the gene, but for RELAX, I
will only use the domain-1.



I had a couple of questions.



1. How does sample size affect RELAX? For the first diverging group, I can
manage up to 10 genes. For the second diverging group I only have 3 genes.
This is because this part of the tree of life has few genomes, and because
whatever genomes have been sequenced they have at times lost this domain
all together.



2. One subclade has completely lost this domain. I have inferred the
phylogenetic relationships from the rest of the gene. However, for RELAX,
an alignment of the domain-only should be used. How should I
include/exclude from a RELAX analysis the genes that have lost the
domain-1? Please note that in an alignment of domain-1, the entry for such
genes (that have undergone loss) would be empty.



A.    Should I remove from the alignment (and the tree) the sequences that
have lost the domain-1?

B.    Should I keep these genes in the alignment as empty sequences? Does
this inform/inhibit RELAX? Please note that in an alignment of domain-1,
the entry for such genes would be empty.

C.    Should I keep these genes in the alignment as empty sequences but not
select them as test or reference?



If you could kindly help!



Thank you,

Aniket


Aniket Sengupta, PhD
Research Associate
Howarth Lab
Biological Sciences
St. John's University

*Mailing address:*
8000 Utopia Pkwy
St. Albert Hall, Room 257
Jamaica, NY 11439
USA

Email: ***@***.***
Website: http://aniketsengupta.weebly.com/
Pronouns: He/Them
----------------------------------------------

*What immortal hand or eye,**Could frame thy fearful symmetry?*
-William Blake
