### ISSUE TITLE
Give confirmation that the job is currently healthy

### ISSUE THREAD

**Issue by stevenweaver** [veg/datamonkey-js#88]
Some become a bit concerned when there is no new output for a while. We should provide some sort of re-assurance that the job is still running and is healthy.

**Comment by spond** [comment]
Dear @stevenweaver,

Yes, that's a good idea. Alternatively, we can work on incorporating progress reports for individual optimizations. That way you can display live progress of a long-term optimization. That might require HyPhy to publish events directly to a socket, or a special parsing code on the client to handle stdout lines that reflect a "progress bar" like behavior. The second solution is simpler, of course. 

Best,
Sergei
